version: '3'

services:
  app:
    image: yas-backend:latest
    container_name: yas-backend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - database
    networks:
      - yas

  database:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - 3306:3306
    volumes:
      - ./db/db_init/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    secrets:
      - mysql_root_password
    networks:
      - yas

networks:
  yas:

secrets:
  mysql_root_password:
    file: ./db/db_secret/mysql_root.secret